import {parseSubtitles,cueIndex,activeCue,youtubeId,formatTime} from './subtitles.mjs';
const $=id=>document.getElementById(id),video=$('video');
const state={kind:null,ready:false,cues:{en:[],tr:[]},offset:{en:0,tr:0},visible:{en:true,tr:true},loop:false,loopIndex:-1,selected:-1,objectUrl:null,generation:0};
let player,apiPromise,noticeTimer,lastHighlight=-2,lastLoop=0;
function notify(text){$('notice').textContent=text;$('notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').hidden=true,6000)}
function baseLang(){return state.cues.en.length?'en':'tr'}
function now(){return state.kind==='youtube'?player?.getCurrentTime?.()||0:video.currentTime||0}
function playing(){return state.kind==='youtube'?player?.getPlayerState?.()===1:!video.paused}
function play(){if(!state.ready)return;state.kind==='youtube'?player.playVideo():video.play().catch(()=>notify('Oynatmak için videonun oynat düğmesine bas.'))}
function pause(){if(state.kind==='youtube')player?.pauseVideo?.();else video.pause()}
function seek(time){time=Math.max(0,time);if(state.kind==='youtube')player?.seekTo?.(time,true);else video.currentTime=time}
function currentIndex(){const lang=baseLang();return cueIndex(state.cues[lang],now(),state.offset[lang])}
function selectCue(index){const lang=baseLang(),c=state.cues[lang][index];if(!state.ready){notify('Önce bir video aç.');return}if(!c)return;state.selected=index;state.loopIndex=index;seek(c.start+state.offset[lang]);play();renderTick()}
function replay(){selectCue(state.loop?state.loopIndex:Math.max(0,currentIndex()))}
function next(delta){const index=state.loop?state.loopIndex:currentIndex();selectCue(Math.max(0,Math.min(state.cues[baseLang()].length-1,index+delta)))}
function setLoop(){state.loop=!state.loop;state.loopIndex=Math.max(0,currentIndex());$('loop').setAttribute('aria-pressed',state.loop);if(state.loop)selectCue(state.loopIndex)}
function toggleLanguage(lang){state.visible[lang]=!state.visible[lang];const button=$(lang==='en'?'toggleEn':'toggleTr');button.setAttribute('aria-pressed',state.visible[lang]);button.querySelector('.eye').textContent=state.visible[lang]?'Açık':'Kapalı';renderList();renderTick()}
function controls(){const hasCues=state.cues[baseLang()].length>0;for(const id of ['previous','next','replay','loop'])$(id).disabled=!hasCues||!state.ready;$('speed').disabled=!state.ready;$('playPause').disabled=!state.ready}
function resetSource(){state.generation++;pause();if(player){player.destroy();player=null}$('youtubeWrap').replaceChildren(Object.assign(document.createElement('div'),{id:'youtube'}));video.removeAttribute('src');video.load();if(state.objectUrl)URL.revokeObjectURL(state.objectUrl);state.objectUrl=null;state.kind=null;state.ready=false;state.loop=false;state.loopIndex=-1;state.selected=-1;state.cues={en:[],tr:[]};state.offset={en:0,tr:0};$('enOffset').value='0';$('trOffset').value='0';$('enFile').value='';$('trFile').value='';document.querySelector('label[for="enFile"]').textContent='Altyazı yükle ↗';document.querySelector('label[for="trFile"]').textContent='Altyazı yükle ↗';$('loop').setAttribute('aria-pressed','false');$('speed').value='1';video.playbackRate=1;$('emptyPlayer').hidden=true;video.hidden=true;$('youtubeWrap').hidden=true;renderList();controls()}
function loadAPI(){if(window.YT?.Player)return Promise.resolve();if(apiPromise)return apiPromise;apiPromise=new Promise((resolve,reject)=>{const timer=setTimeout(()=>{apiPromise=null;reject(new Error('YouTube’a ulaşılamadı. Bağlantını kontrol edip yeniden dene.'))},15000);window.onYouTubeIframeAPIReady=()=>{clearTimeout(timer);resolve()};const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';s.onerror=()=>{clearTimeout(timer);apiPromise=null;s.remove();reject(new Error('YouTube oynatıcısı yüklenemedi.'))};document.head.append(s)});return apiPromise}
async function openUrl(value){let url;try{url=new URL(value);if(!['https:','http:'].includes(url.protocol))throw 0}catch{notify('Geçerli bir https:// bağlantısı gir.');return}const id=youtubeId(value);if(!id&&/(^|\.)youtube\.com$|(^|\.)youtu\.be$/.test(url.hostname)){notify('Tek bir YouTube videosunun bağlantısını gir.');return}resetSource();const generation=state.generation;$('sourceDialog').close();$('videoTitle').textContent=id?'YouTube · '+id:decodeURIComponent(url.pathname.split('/').pop()||url.hostname);if(id){state.kind='youtube';$('sourceType').textContent='YouTube';$('youtubeWrap').hidden=false;try{await loadAPI();if(generation!==state.generation)return;player=new YT.Player('youtube',{videoId:id,width:'100%',height:'100%',playerVars:{playsinline:1,rel:0,origin:location.origin},events:{onReady:()=>{if(generation!==state.generation)return;state.ready=true;controls();const rates=player.getAvailablePlaybackRates();for(const option of $('speed').options)option.disabled=!rates.includes(Number(option.value))},onPlaybackRateChange:e=>{$('speed').value=String(e.data)},onStateChange:e=>{if(e.data===0&&state.loop)selectCue(state.loopIndex)},onError:e=>{state.ready=false;controls();notify([101,150].includes(e.data)?'Bu video başka sitelerde oynatılmaya kapalı. Başka video veya yerel dosya seç.':'YouTube videosu açılamadı (kod '+e.data+'). Başka bir video deneyebilirsin.')}}})}catch(e){if(generation===state.generation)notify(e.message)}}else{state.kind='local';$('sourceType').textContent='Video bağlantısı';video.hidden=false;video.src=url.href;video.load()}}
function openFile(file){if(!file)return;resetSource();state.kind='local';state.objectUrl=URL.createObjectURL(file);video.src=state.objectUrl;video.hidden=false;$('videoTitle').textContent=file.name;$('sourceType').textContent='Bu cihazda';$('sourceDialog').close();video.load()}
function renderList(){const lang=baseLang(),cues=state.cues[lang],list=$('cueList');list.replaceChildren();$('cueCount').textContent=cues.length;if(!cues.length){const box=document.createElement('div');box.className='empty-cues';const heading=document.createElement('h3');heading.textContent='Cümlelerini buraya ekle.';const p=document.createElement('p');p.textContent='EN ve TR için ayrı SRT veya VTT dosyaları yükle. Cümleler videoyla birlikte ilerlesin.';box.append(heading,p);list.append(box)}else{const fragment=document.createDocumentFragment();cues.forEach((c,i)=>{const button=document.createElement('button');button.className='cue';button.dataset.index=i;button.setAttribute('aria-label',formatTime(c.start+state.offset[lang])+' zamanına git');const time=document.createElement('time');time.textContent=formatTime(c.start+state.offset[lang]);button.append(time);for(const l of ['en','tr']){const matched=l===lang?c:activeCue(state.cues[l],c.start+state.offset[lang]+0.05,state.offset[l]);if(matched&&state.visible[l]){const p=document.createElement('p');p.className=l==='tr'?'translation':'';p.textContent=matched.text;button.append(p)}}button.onclick=()=>selectCue(i);fragment.append(button)});list.append(fragment)}lastHighlight=-2;controls();renderTick()}
function renderTick(){const isPlaying=state.ready&&playing();const label=isPlaying?'Duraklat':'Oynat';if($('playPauseText').textContent!==label){$('playPauseText').textContent=label;$('playPauseIcon').textContent=isPlaying?'Ⅱ':'▶';$('playPause').setAttribute('aria-label',label)}const t=now();for(const lang of ['en','tr']){const line=$(lang+'Line');line.hidden=!state.visible[lang];const c=activeCue(state.cues[lang],t,state.offset[lang]);line.textContent=c?.text||(state.cues[lang].length?'…':lang==='en'?'İngilizce altyazını ekle.':'Türkçe altyazını ekle.')}const index=currentIndex();if(index!==lastHighlight){$('cueList').querySelector('.active')?.classList.remove('active');const node=$('cueList').querySelector(`[data-index="${index}"]`);node?.classList.add('active');lastHighlight=index}if(state.loop&&state.ready&&playing()){const lang=baseLang(),c=state.cues[lang][state.loopIndex];if(c&&t>=c.end+state.offset[lang]&&performance.now()-lastLoop>500){lastLoop=performance.now();seek(c.start+state.offset[lang])}}}
async function loadSubtitles(lang,file){if(!file)return;if(file.size>10*1024*1024){notify('Altyazı dosyası 10 MB’dan küçük olmalı.');return}const generation=state.generation;try{const cues=parseSubtitles(await file.text());if(generation!==state.generation)return;if(!cues.length){notify('Dosyada geçerli zaman kodlu altyazı bulunamadı. SRT veya VTT seç.');return}state.cues[lang]=cues;state.loop=false;$('loop').setAttribute('aria-pressed','false');document.querySelector(`label[for="${lang}File"]`).textContent='Değiştir ↗';renderList();notify(`${lang.toUpperCase()}: ${cues.length} altyazı satırı eklendi.`)}catch{notify('Altyazı dosyası okunamadı.')}}
function setOffset(lang,value){if(!Number.isFinite(value)||Math.abs(value)>3600){notify('Zaman farkı −3600 ile 3600 saniye arasında olmalı.');$(lang+'Offset').value=state.offset[lang];return}state.offset[lang]=Math.round(value*10)/10;$(lang+'Offset').value=state.offset[lang];renderList()}
for(const id of ['openSource','emptyOpen'])$(id).onclick=()=>$('sourceDialog').showModal();$('closeDialog').onclick=()=>$('sourceDialog').close();$('sourceForm').onsubmit=e=>{e.preventDefault();openUrl($('sourceUrl').value.trim())};$('videoFile').onchange=e=>{openFile(e.target.files[0]);e.target.value=''};
for(const lang of ['en','tr']){$(lang+'File').onchange=e=>loadSubtitles(lang,e.target.files[0]);$(lang+'Offset').onchange=e=>setOffset(lang,Number(e.target.value));$(lang==='en'?'toggleEn':'toggleTr').onclick=()=>toggleLanguage(lang)}
for(const b of document.querySelectorAll('[data-delta]'))b.onclick=()=>setOffset(b.dataset.lang,state.offset[b.dataset.lang]+Number(b.dataset.delta));
$('playPause').onclick=()=>playing()?pause():play();$('replay').onclick=replay;$('previous').onclick=()=>next(-1);$('next').onclick=()=>next(1);$('loop').onclick=setLoop;$('focus').onclick=()=>{const on=document.body.classList.toggle('focus-mode');$('focus').setAttribute('aria-pressed',on)};
$('speed').onchange=e=>{const rate=Number(e.target.value);if(state.kind==='youtube')player?.setPlaybackRate(rate);else video.playbackRate=rate};
video.addEventListener('loadedmetadata',()=>{if(state.kind!=='local')return;state.ready=true;for(const option of $('speed').options)option.disabled=false;controls()});video.addEventListener('error',()=>{if(state.kind==='local'){state.ready=false;controls();notify('Video açılamadı. Tarayıcının desteklediği MP4/WebM dosyası veya doğrudan video bağlantısı kullan.')}});video.addEventListener('ended',()=>{if(state.loop)selectCue(state.loopIndex)});
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.altKey||e.metaKey||e.target.closest('input,textarea,select,[contenteditable]')||$('sourceDialog').open)return;if(e.key===' '&&e.target.closest('button'))return;const key=e.key.toLowerCase();const actions={'r':replay,'arrowleft':()=>next(-1),'arrowright':()=>next(1),'l':()=>{if(!$('loop').disabled)setLoop()},'e':()=>toggleLanguage('en'),'t':()=>toggleLanguage('tr'),'f':()=>$('focus').click(),' ':()=>playing()?pause():play()};if(actions[key]){e.preventDefault();actions[key]()}});
setInterval(renderTick,60);controls();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'replay_current_sentence',description:'Replay the current subtitle sentence in the selected video.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).length)throw new Error('No arguments accepted');if(!state.ready||!state.cues[baseLang()].length)throw new Error('Load a video and subtitles first');replay();return{sentence:state.cues[baseLang()][state.loopIndex]?.text}}})).catch(()=>{})}catch{}}
